apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frappe-crm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: prod
  source:
    repoURL: https://helm.erpnext.com
    chart: erpnext
    targetRevision: 8.0.51
    helm:
      valuesObject:
        image:
          repository: ghcr.io/frappe/crm
          tag: v1.71.3
          pullPolicy: IfNotPresent

        mariadb:
          enabled: true
        postgresql:
          enabled: false

        persistence:
          worker:
            enabled: true
            size: 8Gi
            storageClass: local-path
            accessModes:
              - ReadWriteOnce
          logs:
            enabled: true
            size: 4Gi
            storageClass: local-path
            accessModes:
              - ReadWriteOnce

        nginx:
          defaultTopologySpread:
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway

        worker:
          defaultTopologySpread:
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway

        jobs:
          configure:
            enabled: true
            fixVolume: true
          createSite:
            enabled: true
            siteName: crm.devopian.com
            dbType: mariadb
            adminExistingSecret: frappe-crm-passwords
            adminExistingSecretKey: admin-password
            installApps:
              - crm

  destination:
    server: https://kubernetes.default.svc
    namespace: frappe-crm-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: frappe-crm-mariadb-subchart
      namespace: frappe-crm-prod
      jsonPointers:
        - /data
