apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azp-agent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infra
  source:
    repoURL: git@github.com:jctekdev/k8s-manifests-public.git
    targetRevision: main
    path: azp-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: azp-agent-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
