apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.139
    helm:
      valuesObject:
        controller:
          admin:
            createSecret: false
          installPlugins:
            - kubernetes:latest
            - workflow-aggregator:latest
            - git:latest
          servicePort: 8080
          targetPort: 8080
          agentListenerEnabled: true
          agentListenerPort: 50000
        persistence:
          enabled: true
          size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-infra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true