apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbeaver
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: git@github.com:JCTekDev/k8s-manifests-public.git
    targetRevision: main
    path: cloudbeaver
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudbeaver-infra
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
