apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: cnpg-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  source:
    repoURL: https://github.com/cloudnative-pg/artifacts
    # Fija la versión menor que quieras gestionar (p.ej., release-1.27).
    # Así controlas upgrades dentro de esa menor con PRs revisados.
    targetRevision: release-1.27
    path: manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Útil en operadores/CRDs para evitar sobrescribir innecesario
      - ApplyOutOfSyncOnly=true
      # Server-side apply suele ir mejor con CRDs grandes
      - ServerSideApply=true