apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: infra

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.4
    helm:
      valuesObject:
        controller:
          admin.username: admin
          admin.password: admin
          service.type: ClusterIP
        persistence:
          enabled: true
          size: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-infra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true