apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: infra
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.19.0
    helm:
      valuesObject:
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: ""
        operator:
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        logging:
          level: info
  destination:
    server: https://kubernetes.default.svc
    namespace: keda-infra
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
