apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: "2.19.0"
    helm:
      releaseName: keda
      valuesObject:
        namespace: keda-infra
        serviceAccount:
          create: true
          name: keda-operator
        replicaCount: 2
        image:
          repository: ghcr.io/kedacore/keda-operator
          tag: "2.14.4"
        metricsServer:
          useHostNetwork: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        rbac:
          create: true
        admissionWebhooks:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda-infra
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
